-------------------------------------------------------------------------------
Test set: ifmt.cba.negocio.TipoPreparoNegocio_TipoPreparoDAO_UnitarioTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.036 s <<< FAILURE! -- in ifmt.cba.negocio.TipoPreparoNegocio_TipoPreparoDAO_UnitarioTest
ifmt.cba.negocio.TipoPreparoNegocio_TipoPreparoDAO_UnitarioTest.exclusaoTipoPreparo -- Time elapsed: 0.007 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception thrown: ifmt.cba.negocio.NegocioException: Ja existe esse tipo de preparo
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:84)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:53)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:36)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3164)
	at ifmt.cba.negocio.TipoPreparoNegocio_TipoPreparoDAO_UnitarioTest.exclusaoTipoPreparo(TipoPreparoNegocio_TipoPreparoDAO_UnitarioTest.java:55)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: ifmt.cba.negocio.NegocioException: Ja existe esse tipo de preparo
	at ifmt.cba.negocio.TipoPreparoNegocio.inserir(TipoPreparoNegocio.java:36)
	at ifmt.cba.negocio.TipoPreparoNegocio_TipoPreparoDAO_UnitarioTest.lambda$exclusaoTipoPreparo$10(TipoPreparoNegocio_TipoPreparoDAO_UnitarioTest.java:56)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:49)
	... 6 more

ifmt.cba.negocio.TipoPreparoNegocio_TipoPreparoDAO_UnitarioTest.inserirTipoPreparo -- Time elapsed: 0.006 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception thrown: ifmt.cba.negocio.NegocioException: Ja existe esse tipo de preparo
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:84)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:53)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:36)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3164)
	at ifmt.cba.negocio.TipoPreparoNegocio_TipoPreparoDAO_UnitarioTest.inserirTipoPreparo(TipoPreparoNegocio_TipoPreparoDAO_UnitarioTest.java:23)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: ifmt.cba.negocio.NegocioException: Ja existe esse tipo de preparo
	at ifmt.cba.negocio.TipoPreparoNegocio.inserir(TipoPreparoNegocio.java:36)
	at ifmt.cba.negocio.TipoPreparoNegocio_TipoPreparoDAO_UnitarioTest.lambda$inserirTipoPreparo$2(TipoPreparoNegocio_TipoPreparoDAO_UnitarioTest.java:24)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:49)
	... 6 more

